aplicacionweb/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
#Pantallas iniciales
from .views import home, cooperativo, deckbuilding, eurogames, familiar, solitarios

#Pantallas de usuario
from .views import iniciar_sesion
from .views import registrousuario #Verificar si esto aun tiene utilidad
from .views import recuperarcontrasena
from .views import editarperfil

#Pant para panel de moderacion
from .views import panel_moderacion
from .views import form_mod_usuario
from .views import form_usuario
from .views import form_del_usuario

#registro de clientes
from .views import reg_clientes
from .views import iniciar_sesion
from .views import cerrar_sesion

#Panel de administracion para manejar productos
from .views import panel_create_productos
from .views import panel_productos
from .views import form_mod_producto
from .views import form_del_producto

from .views import agregar_al_carrito
from .views import carrito_compras
from .views import quitar_del_carrito
from .views import ordenes_compra
from .views import ver_pedidos
from .views import realizar_compra
from .views import ver_todos_pedidos
from .views import panel_pedidos
from .views import borrar_pedido
from .views import recuperar_contrasena
from .views import cambiar_contrasena




urlpatterns = [
    path('', home, name='home'),
    path('cooperativo/', cooperativo, name='cooperativo'),
    path('deckbuilding/', deckbuilding, name='deckbuilding'),
    path('eurogames/', eurogames, name='eurogames'),
    path('familiar/', familiar, name='familiar'),
    path('solitarios/', solitarios, name='solitarios'),
    path('iniciarsesion/', iniciar_sesion, name='iniciarsesion'),
    path('registrousuario/', registrousuario, name='registrousuario'),
    path('recuperarcontrasena/', recuperarcontrasena, name='recuperarcontrasena'),
    path('editarperfil/', editarperfil, name='editarperfil'),
    path('panel_moderacion/', panel_moderacion, name='panel_moderacion'),
    
    path('form_usuario/', form_usuario, name='form_usuario'),
    path('form_mod_usuario/<id>', form_mod_usuario, name='form_mod_usuario'),
    path('form_del_usuario/<id>', form_del_usuario, name='form_del_usuario'),
    path('reg_clientes/', reg_clientes, name='reg_clientes'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('panel_create_productos/', panel_create_productos, name='panel_create_productos'),
    path('panel_productos/', panel_productos, name='panel_productos'),
    path('form_mod_producto/<int:id>/', views.form_mod_producto, name='form_mod_producto'),
    path('form_del_producto/<id>', form_del_producto, name='form_del_producto'),
    
    path('agregar_al_carrito/<str:nombre_producto>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito_compras/', carrito_compras, name='carrito_compras'),
    path('quitar_del_carrito/<str:nombre_producto>/', views.quitar_del_carrito, name='quitar_del_carrito'),
    path('ordenes_compra/', views.ordenes_compra, name='ordenes_compra'),
    path('realizar_compra/', views.realizar_compra, name='realizar_compra'),
    
    path('ver_pedidos/', views.ver_pedidos, name='ver_pedidos'),
    path('ver_todos_pedidos/', views.ver_todos_pedidos, name='ver_todos_pedidos'),
    path('panel_pedidos/', views.panel_pedidos, name='panel_pedidos'),
    path('borrar_pedido/<int:pedido_id>/', views.borrar_pedido, name='borrar_pedido'),
    path('recuperar_contrasena/', views.recuperar_contrasena, name='recuperar_contrasena'),
    path('cambiar_contrasena/<int:user_id>/', cambiar_contrasena, name='cambiar_contrasena'),
    path('agregar_categorias/', views.agregar_categorias, name='agregar_categorias'),
    path('categorias_proveedores/', views.categorias_proveedores, name='categorias_proveedores'),
    path('borrar_categoria/<int:id>/', views.borrar_categoria, name='borrar_categoria'),
    path('borrar_proveedor/<int:id>/', views.borrar_proveedor, name='borrar_proveedor'),
]

proyectoweb_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#importacion de libreria para autentificacion de usuario rest api
from rest_api.viewsLogin import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicacionweb.urls')),
    path('api/',include('rest_api.urls')),
    path('login/', login, name='login'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('productos/', views.lista_Productos, name='lista_Productos'),
    path('categorias/', views.lista_Categorias, name='lista_Categorias'),
]

aplicacionweb/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

#NOTA: Para las imagenes tuve que instalar "python -m pip install Pillow" para que funcionara

# #CLASE DE USUARIO (esta tabla se puede quitar si se desea, ya que se esta usando la tabla User de Django)
class Usuario(models.Model):
    email = models.EmailField(max_length=200, verbose_name='Email', unique=True, primary_key=True)
    nombre = models.CharField(max_length=50, verbose_name='Nombre')
    apellido = models.CharField(max_length=50, verbose_name='Apellido')
    nombreUsuario = models.CharField(max_length=50, unique=True, verbose_name='Usuario')
    contrasena = models.CharField(max_length=50, verbose_name='Contrasena')
    direccion = models.CharField(max_length=200, verbose_name='Direccion')
    
    def __str__(self):
        return self.get_code_name()
    
    def get_code_name(self):
        return f"Email asociado: {self.email} - {self.nombre} - {self.apellido}"
    
    
    
#CREANDO LAS CLASES
class Categoria(models.Model):
    CATEGORIAS = [
        ('Familiar', 'Familiar'),
        ('Cooperativo', 'Cooperativo'),
        ('Eurogame', 'Eurogame'),
        ('Deckbuilding', 'Deckbuilding'),
        ('Solitario', 'Solitario'),
    ]

    nombre = models.CharField(max_length=50, choices=CATEGORIAS)

    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    TIPOS_PROVEEDOR = [
        ('Nacional', 'Nacional'),
        ('Extranjero', 'Extranjero'),
    ]

    tipo = models.CharField(max_length=10, choices=TIPOS_PROVEEDOR, default='Nacional')

    def __str__(self):
        return self.tipo

class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True)
    nombreProducto = models.CharField(max_length=50, verbose_name='Nombre')
    precioProducto = models.IntegerField(verbose_name='Precio')
    descripcionProducto = models.TextField(max_length=200, verbose_name='Descripcion')
    imagenProducto = models.ImageField(upload_to='productos', null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreProducto

class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='CarritoProducto')

class CarritoProducto(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.usuario.username} - {self.producto.nombreProducto}'

class PedidoProducto(models.Model):
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='PedidoProducto')
    fecha_pedido = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Pedido {self.id} - {self.usuario.username}'


#Vamos a usar esto para extender una tabla hacia User, para que adhiera dos campos: palabra clave para recuperar contraseña y un avatar
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    palabra_clave = models.CharField(max_length=100)
    

aplicacionweb/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuario
from .models import Producto


#creamos nuestra clase para el fomrulario desde la base de datos

#UsuarioForm sirve para crear un nuevo usuario (usando el modelo Usuario)
class UsuarioForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = ['email', 'nombre', 'apellido', 'nombreUsuario', 'contrasena', 'direccion']

#ClienteForm sirve para crear un nuevo cliente (usando el modelo Usuario)
class ClienteForm(ModelForm):
    avatar = forms.ImageField(required=False)  # Campo para el avatar
    palabra_clave = forms.CharField(required=False)  # Campo para la palabra clave
    class Meta:
        model = Usuario
        fields = ['email', 'nombre', 'apellido', 'nombreUsuario', 'contrasena', 'direccion', 'avatar', 'palabra_clave']

#ProductoForm sirve para crear un nuevo producto (usando el modelo Producto)
class ProductoForm(ModelForm):
    
    class Meta:
        model = Producto
        fields = ['nombreProducto', 'precioProducto', 'descripcionProducto', 'imagenProducto', 'categoria', 'proveedor']
        

aplicacionweb/templates/aplicacionweb/cambiar_contrasena.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ludoteca Duoc - Solitarios</title>
    <link rel="stylesheet" href="{% static '/css/reg_clientes-style.css' %}">
    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>

</head>


<body>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Cambiar contraseña</button>
</form>



</body>

</html>

aplicacionweb/templates/aplicacionweb/carrito_compras.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ludoteca Duoc</title>

    <link rel="stylesheet" href="{% static '/css/carrito-style.css' %}">

    <style>
        .item-info {
            width: 200px;  /* Ajusta este valor según tus necesidades */
        }
    </style>

    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>
    
</head>

<body>

    <h1>Mi Carrito</h1>

    {% for item in carrito_productos %}
    <div class="item">
        <h2 class="item-info">{{ item.producto.nombreProducto }}</h2>
        <p class="item-info precio">Precio: ${{ item.producto.precioProducto }}</p>
        <p class="item-info">Cantidad: {{ item.cantidad }}</p>
        <div class="botones">
            <!-- Botón de Quitar -->
            <form method="post" action="{% url 'quitar_del_carrito' item.producto.nombreProducto %}" onsubmit="myButton.disabled = true; return true;">
                {% csrf_token %}
                <button type="submit" id="myButton">Quitar</button>
            </form>
            <!-- Botón de Agregar -->
            <form method="post" action="{% url 'agregar_al_carrito' item.producto.nombreProducto %}" onsubmit="myButton2.disabled = true; return true;">
                {% csrf_token %}
                <button type="submit" id="myButton2">Agregar</button>
            </form>
        </div>
    </div>
    {% empty %}
    <p>No hay productos en el carrito.</p>
    {% endfor %}
    
    <!-- Total -->
    <p class="total">Total: ${{ total }}</p>
    
    <!-- Botón de Realizar Compra -->
    <form method="post" action="{% url 'realizar_compra' %}" onsubmit="compraButton.disabled = true; return true;">
        {% csrf_token %}
        <button type="submit" id="compraButton" {% if not carrito_productos %}disabled{% endif %}>Realizar Compra</button>
    </form>

    <!-- Botón de Inicio -->
    <div class="boton-inicio-container">
        <a href="{%  url 'home' %}" class="navbar-link boton-inicio"><i class="fas fa-home"></i> Inicio</a>
    </div>

</body>

{% comment %} <footer class="footer">
    <p>@Todos los derechos reservados</p>
    <div class="social-icons">
        <a href="https://www.facebook.com/DuocUC/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://twitter.com/DuocUC"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com/duocuc_cl/"><i class="fab fa-instagram"></i></a>
    </div>
</footer> {% endcomment %}

</html>

aplicacionweb/templates/aplicacionweb/categorias_proveedores.html
<!DOCTYPE html>

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ludoteca Duoc</title>

    <link rel="stylesheet" href="{% static '/css/paneladm-style.css' %}">

    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>
    
</head>

<body>
<html>
<head>
    <title>Ver y borrar Categorías y Proveedores</title>
</head>
<body>
    <h1>Categorías</h1>
    <ul>
        {% for categoria in categorias %}
            <li>
                {{ categoria.nombre }}
                <a href="{% url 'borrar_categoria' categoria.id %}">Borrar</a>
            </li>
        {% empty %}
            <li>No hay categorías.</li>
        {% endfor %}
    </ul>
</body>
</html>

<h1>Proveedores</h1>
<ul>
    {% for proveedor in proveedores %}
        <li>
            {{ proveedor.tipo }}
            <a href="{% url 'borrar_proveedor' proveedor.id %}">Borrar</a>
        </li>
    {% empty %}
        <li>No hay proveedores.</li>
    {% endfor %}
</ul>


</body>

<li class="navbar-item"><a href="{%  url 'home' %}" class="navbar-link"><i class="fas fa-home"></i> Inicio</a></li>


{% comment %} <footer class="footer">
    <p>@Todos los derechos reservados</p>
    <div class="social-icons">
        <a href="https://www.facebook.com/DuocUC/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://twitter.com/DuocUC"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com/duocuc_cl/"><i class="fab fa-instagram"></i></a>
    </div>
</footer> {% endcomment %}

</html>

aplicacionweb/templates/aplicacionweb/deckbuilding.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ludoteca Duoc - Deckbuilding</title>
    <link rel="stylesheet" href="{% static '/css/website-catalogo-style.css' %}">
    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>

</head>


<body>

    <div class="button-container">



        {% if user.is_superuser %}
    <a href="{%  url 'panel_moderacion' %}">
        <button class="admin-button">USERS ADMIN</button>
    </a>
    <a href="{%  url 'panel_productos' %}">
        <button class="admin-button">PRODUCTOS ADMIN</button>
    </a>
    <a href="{%  url 'panel_pedidos' %}">
        <button class="admin-button">PEDIDOS ADMIN</button>
    {% endif %}
    
    {% if user.is_authenticated %}
    <div>
        <a href="{%  url 'ordenes_compra' %}"><button>Ordenes de compra</button></a>
        <a href="{%  url 'carrito_compras' %}"><button>Carrito</button></a>
        <a href="{%  url 'editarperfil' %}"><button>Mi cuenta</button></a>
        <a href="{% url 'cerrar_sesion' %}"><button>Cerrar sesión</button></a>
        <div style="margin-top: 20px; margin-left: 600px;"> <!-- Esta linea mueve a los lados el avatar y msj -->
            {% if user.userprofile.avatar %}
                <img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }}'s avatar" style="width: 100px; height: 100px;">
            {% else %}
                <img src="{% static '/Img/OIG4.jpg' %}" alt="Default avatar" style="width: 100px; height: 100px;">
            {% endif %}
            <h3 style="margin-left: -10px;">
                ¡Bienvenido {{ user.username }}!
            </h3>
        </div>
    </div>
{% else %}
    <div class="button-container">
        <a href="{%  url 'reg_clientes' %}"><button>Crear Cuenta</button></a>
        <a href="{%  url 'iniciar_sesion' %}"><button>Iniciar Sesión</button></a>
    </div>
{% endif %}
    
    </div>
    

    <img src="{% static 'Img/ludotecaduoc-logo.png' %}" alt="bibliotecaduoc" id="logo">

    <nav class="navbar">
        <ul class="navbar-list">
            <li class="navbar-item"><a href="{%  url 'home' %}" class="navbar-link"><i class="fas fa-home"></i> Inicio</a></li>
            <li class="navbar-item"><a href="{%  url 'familiar' %}" class="navbar-link">Familiar</a></li>
            <li class="navbar-item"><a href="{%  url 'cooperativo' %}" class="navbar-link">Cooperativo</a></li>
            <li class="navbar-item"><a href="{%  url 'eurogames' %}" class="navbar-link">EuroGames</a></li>
            <li class="navbar-item"><a href="{%  url 'solitarios' %}" class="navbar-link">Solitarios</a></li>
            <li class="navbar-item"><span class="navbar-text">Valor del dólar: {{ valor_dolar_hoy }}</span></li>
        </ul>
    </nav>


        <div class="container border-box">
        <h1>DECKBUILDING</h1>

            <!-- Producto: Marvel Champions-->
            {% for producto in productos %}
            {% if producto.nombreProducto == "Marvel Champions" %}
                <div class="categoria">
                    <div class="card-12 card-sm-6 card-md-4">
                        <img src="{{ producto.imagenProducto.url }}" alt="{{ producto.nombreProducto }}">
                        <div class="card-content">
                            <h2>{{ producto.nombreProducto }}</h2>
                            <p>{{ producto.descripcionProducto }}</p>
                            <p class="precio">Precio: ${{ producto.precioProducto }}</p>
                            <!-- Botón de Comprar -->
                            {% if user.is_authenticated %}
                                <form method="post" action="{% url 'agregar_al_carrito' producto.nombreProducto %}" onsubmit="myButton.disabled = true; return true;">
                                    {% csrf_token %}
                                    <button type="submit" id="myButton" class="buy-button">Comprar</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <!-- Producto: Hero Realms-->
        {% for producto in productos %}
    {% if producto.nombreProducto == "Hero Realms" %}
        <div class="categoria">
            <div class="card-12 card-sm-6 card-md-4">
                <img src="{{ producto.imagenProducto.url }}" alt="{{ producto.nombreProducto }}">
                <div class="card-content">
                    <h2>{{ producto.nombreProducto }}</h2>
                    <p>{{ producto.descripcionProducto }}</p>
                    <p class="precio">Precio: ${{ producto.precioProducto }}</p>
                    <!-- Botón de Comprar -->
                    {% if user.is_authenticated %}
                        <form method="post" action="{% url 'agregar_al_carrito' producto.nombreProducto %}" onsubmit="myButton.disabled = true; return true;">
                            {% csrf_token %}
                            <button type="submit" id="myButton" class="buy-button">Comprar</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}
        </div>
    </div> 

 
    <footer class="footer">
        <p>@Todos los derechos reservados</p>
        <div class="social-icons">
            <a href="https://www.facebook.com/DuocUC/"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/DuocUC"><i class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/duocuc_cl/"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="api-links">
            <a href="http://127.0.0.1:8000/api/productos/">API interna: productos</a>
            <a href="http://127.0.0.1:8000/api/categorias/">API interna: categorias</a>
        </div>
    </footer>

</body>


</html>

aplicacionweb/templates/aplicacionweb/editarperfil.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Perfil</title>

    <!-- *** LIBRERIA DE ESTILOS (6.4.0 RECOMENDADA EN VIDEO DE CLASE *** -->
    <link rel="stylesheet" href="{% static '/css/forms-style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        #avatar {
            width: 100px;
            height: 100px;
            object-fit: cover;
        }
    </style>

</head>
<body>

    <h1 id="title">Editar Perfil</h1>

    {% load static %}
    
    <form method="post" id="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_first_name">Nombre</label>
        <input type="text" id="id_first_name" name="first_name" value="{{ user.first_name }}">
    </div>
    <div class="form-group">
        <label for="id_last_name">Apellido</label>
        <input type="text" id="id_last_name" name="last_name" value="{{ user.last_name }}">
    </div>
    <div class="form-group">
        <label for="id_avatar">Avatar actual</label>
        {% if user.userprofile.avatar %}
            <img id="avatar" src="{{ user.userprofile.avatar.url }}" alt="Avatar actual">
        {% else %}
            <img id="avatar" src="{% static 'Img/OIG4.jpg' %}" alt="Default avatar">
        {% endif %}
        <label for="id_avatar">Cambiar avatar</label>
        <input type="file" id="id_avatar" name="avatar">
    </div>
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Actualizar perfil</button>
</form>

    <a href="{% url 'home' %}" class="btn"><i class="fas fa-home"></i> Regresar a HOME</a>


</body>

</html>

aplicacionweb/templates/aplicacionweb/form_mod_usuario.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ludoteca Duoc - cooperativo</title>
    <link rel="stylesheet" href="{% static '/css/panelformularios-adm.css' %}">
    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>

</head>

  <body>
    <img src="{% static '/Img/editar-paneladmin.png' %}" alt="DATABASE USUARIOS">
    <h3>Modificacion de usuario</h3>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
    <div class="row">
        <form method="post" action="" id="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ user_form.as_table }}
                {{ profile_form.as_table }}
            </div>
    
            <input type="submit" class="btn btn-danger" id="enviar" value="Modificar">
            <input type="reset" class="btn btn-primary" id="limpiar" value="Limpiar">
            <div id="error" class="alert alert-danger" role="alert"></div>
        </form>
        <div class="alert alert-success" role="alert">
            {{ mensaje }}
        </div>
    </div>

<a href="{% url 'home' %}" class="btn"><i class="fas fa-home"></i> Regresar a HOME</a>
<a href="{% url 'panel_moderacion' %}" class="btn"><i class="fas fa-home"></i> PANEL ADMIN</a>


</body>

</html>

aplicacionweb/templates/aplicacionweb/panel_pedidos.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RetroGames - Free To Play</title>
    <link rel="stylesheet" href="{% static '/css/paneladm-style.css' %}">
    <script src="https://kit.fontawesome.com/25ac30d53f.js"></script>

</head>

<body>
<h1>Panel de pedidos</h1>
{% if pedidos %}
    <h2>Pedidos registrados</h2>
{% else %}
    <p>No tienes ningún pedido registrado.</p>
{% endif %}

<div class="list-group">
    {% for pedido in pedidos %}
    <a href="#" class="list-group-item list-group-item-action mb-3" style="margin-bottom: 20px;">
        <div class="card" style="margin-bottom: 20px;">
            <div class="card-body d-flex justify-content-between"> <!-- Añade las clases d-flex y justify-content-between -->
                <div> <!-- Añade este div para agrupar la información del pedido -->
                    <h5 class="card-title">ID del pedido: {{ pedido.id }}</h5>
                    <p class="card-text">Usuario: {{ pedido.usuario.username }}</p>
                    <p class="card-text">Fecha del pedido: {{ pedido.fecha_pedido }}</p>
                    <p class="card-text">Productos:</p>
                    <ul class="mb-3">
                        {% for productopedido in pedido.pedidoproducto_set.all %}
                        <li>{{ productopedido.producto.nombreProducto }} - Cantidad: {{ productopedido.cantidad }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <form action="{% url 'borrar_pedido' pedido.id %}" method="post" class="mt-3" style="margin-top: 20px;">
                    {% csrf_token %}
                    <input type="submit" value="Borrar pedido" class="btn btn-danger">
                </form>
            </div>
        </div>
    </a>
{% endfor %}
</div>

<div style="display: flex; justify-content: space-between; margin-top: 20px;">
    <a href="{% url 'home' %}" class="btn"><i class="fas fa-home"></i> Regresar a HOME</a>
</div>

<footer class="footer">
    <div class="social-icons">
        <a href="https://www.facebook.com/DuocUC/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://twitter.com/DuocUC"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com/duocuc_cl/"><i class="fab fa-instagram"></i></a>
    </div>
</footer>

</body>

</html>